apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apples.app.example.org
spec:
  group: app.example.org
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                volume:
                  type: string
  scope: Namespaced
  names:
    plural: apples
    kind: Apple
