apiVersion: servicebinding.io/v1alpha3
kind: ClusterWorkloadResourceMapping
metadata:
   name: apples.app.example.org
spec:
   versions:
   - version: "*"
     containers:
        - path: .spec.containers[*]
